実験用回路のディレクトリ名を入力してください
Traceback (most recent call last):
  File "Main.py", line 45, in <module>
    dir_name = input()
OSError: [Errno 9] Bad file descriptor
実験用回路のディレクトリ名を入力してください
Traceback (most recent call last):
  File "Main.py", line 45, in <module>
    dir_name = input()
OSError: [Errno 9] Bad file descriptor
実験用回路のディレクトリ名を入力してください
Traceback (most recent call last):
  File "Main.py", line 45, in <module>
    dir_name = input()
OSError: [Errno 9] Bad file descriptor
実験用回路のディレクトリ名を入力してください
Traceback (most recent call last):
  File "Main.py", line 45, in <module>
    dir_name = input()
OSError: [Errno 9] Bad file descriptor
実験用回路のディレクトリ名を入力してください
Traceback (most recent call last):
  File "Main.py", line 45, in <module>
    dir_name = input()
OSError: [Errno 9] Bad file descriptor
実験用回路のディレクトリ名を入力してください
Traceback (most recent call last):
  File "Main.py", line 45, in <module>
    dir_name = input()
OSError: [Errno 9] Bad file descriptor
実験用回路のディレクトリ名を入力してください
Traceback (most recent call last):
  File "Main.py", line 45, in <module>
    dir_name = input()
OSError: [Errno 9] Bad file descriptor
実験用回路のディレクトリ名を入力してください
Traceback (most recent call last):
  File "Main.py", line 45, in <module>
    dir_name = input()
OSError: [Errno 9] Bad file descriptor
実験用回路のディレクトリ名を入力してください
Traceback (most recent call last):
  File "Main.py", line 45, in <module>
    dir_name = input()
OSError: [Errno 9] Bad file descriptor
